from fastapi import APIRouter
from fastapi import Depends
from fastapi.responses import FileResponse

from sqlalchemy.orm import Session

from app.utils.dependencies import get_db
from app.models.parcel import Parcel

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib import colors
from datetime import datetime

from reportlab.lib.styles import (
    getSampleStyleSheet
)

from reportlab.lib.units import inch


router = APIRouter(
    prefix="/reports",
    tags=["Reports"]
)


@router.get("/download-pdf")
def download_pdf_report(
    db: Session = Depends(get_db)
):

    total_parcels = db.query(
        Parcel
    ).count()

    delivered = db.query(
        Parcel
    ).filter(
        Parcel.status == "Delivered"
    ).count()

    failed = db.query(
        Parcel
    ).filter(
        Parcel.status == "FailedDelivery"
    ).count()

    failed_parcels = db.query(
        Parcel
    ).filter(
        Parcel.status == "FailedDelivery"
    ).all()

    pending = total_parcels - (
        delivered + failed
    )

    success_rate = 0

    if total_parcels > 0:

        success_rate = round(
            (delivered / total_parcels) * 100,
            2
        )

    file_path = "delivery_report.pdf"

    doc = SimpleDocTemplate(
        file_path
    )

    styles = getSampleStyleSheet()

    elements = []

    elements.append(
        Paragraph(
            "FINAL MILE DELIVERY HUB",
            styles["Title"]
        )
    )

    elements.append(
        Paragraph(
            "ADMIN DELIVERY REPORT",
            styles["Heading2"]
        )
    )

    elements.append(
        Spacer(1, 0.2 * inch)
    )

    elements.append(
        Paragraph(
            f"Generated On: {datetime.now().strftime('%d-%m-%Y %I:%M %p')}",
            styles["Normal"]
        )
    )

    elements.append(
        Spacer(1, 0.3 * inch)
    )

    summary_data = [

        ["Metric", "Value"],

        ["Total Parcels", str(total_parcels)],

        ["Delivered Parcels", str(delivered)],

        ["Failed Deliveries", str(failed)],

        ["Pending Deliveries", str(pending)],

        ["Success Rate", f"{success_rate}%"]

    ]

    summary_table = Table(summary_data)

    summary_table.setStyle(

        TableStyle([

            ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),

            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),

            ('GRID', (0, 0), (-1, -1), 1, colors.black),

            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),

            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),

            ('BOTTOMPADDING', (0, 0), (-1, 0), 12)

        ])

    )

    elements.append(summary_table)

    elements.append(
        Spacer(1, 0.4 * inch)
    )

    elements.append(
        Paragraph(
            "FAILED DELIVERY DETAILS",
            styles["Heading2"]
        )
    )

    failed_data = [

        [
            "Tracking Number",
            "Reason"
        ]

    ]

    for parcel in failed_parcels:

        failed_data.append(

            [
                parcel.tracking_number,
                parcel.failure_reason or "N/A"
            ]

        )

    failed_table = Table(failed_data)

    failed_table.setStyle(

        TableStyle([

            ('BACKGROUND', (0, 0), (-1, 0), colors.red),

            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),

            ('GRID', (0, 0), (-1, -1), 1, colors.black),

            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),

            ('ALIGN', (0, 0), (-1, -1), 'CENTER')

        ])

    )

    elements.append(failed_table)


    elements.append(
        Spacer(1, 0.5 * inch)
    )

    elements.append(
        Paragraph(
            "Generated by Final Mile Delivery Hub Management System",
            styles["Italic"]
        )
    )

    doc.build(elements)

    return FileResponse(
        path=file_path,
        media_type="application/pdf",
        filename="delivery_report.pdf"
    )